name: 'Deploy Auth Service'
description: 'Deploys the auth service'

inputs:
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true
  auth_db_id:
    description: 'The ID of the AUTH_DB D1 database'
    required: true
  domain_worker_names:
    description: 'JSON string of domain worker names for worker-to-worker bindings'
    required: true
  GH_PERSONAL_ACCESS_TOKEN:
    description: 'GitHub Personal Access Token'
    required: true
  brevo_api_key:
    description: 'Brevo API key for email service'
    required: true
  stripe_secret_key:
    description: 'Stripe secret key for payment processing'
    required: true
  stripe_webhook_secret:
    description: 'Stripe webhook secret for webhook verification'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: './auth-service'
      shell: bash
      run: 'npm install'

    # Due to the bug in the cloudflare terraform provider, we need to manually
    # update the wrangler.toml file to include the AUTH_DB database ID.
    - name: Update wrangler.toml
      working-directory: './auth-service'
      shell: bash
      run: |
        sed -i "s/database_id = \"\"/database_id = \"${{ inputs.auth_db_id }}\"/" wrangler.toml

    # Add worker-to-worker binding for each domain worker.
    # These are the 1 to many bindings from the auth-service to the domain workers.
    - name: Add worker-to-worker bindings
      working-directory: './auth-service'
      shell: bash
      run: |
        # Parse the domain worker names JSON
        DOMAIN_WORKERS='${{ inputs.domain_worker_names }}'
        
        # Add worker-to-worker bindings to wrangler.toml
        echo "" >> wrangler.toml
        echo "# Worker-to-worker bindings" >> wrangler.toml
        echo "$DOMAIN_WORKERS" | jq -r 'to_entries[] | "[[services]]\nbinding = \"" + .value + "\"\nservice = \"" + .value + "\""' >> wrangler.toml

    # Deploy the worker first (without secrets)
    - name: Deploy Worker
      working-directory: './auth-service'
      shell: bash
      run: 'npx wrangler deploy'
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}

    # Set Brevo API key as a Wrangler secret (after worker exists)
    - name: Set Brevo API Key Secret
      working-directory: './auth-service'
      shell: bash
      run: |
        echo "${{ inputs.brevo_api_key }}" | npx wrangler secret put BREVO_API_KEY
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}

    # Set Stripe secrets as Wrangler secrets
    - name: Set Stripe Secrets
      working-directory: './auth-service'
      shell: bash
      run: |
        echo "${{ inputs.stripe_secret_key }}" | npx wrangler secret put STRIPE_SECRET_KEY
        
        # Retrieve the webhook secret from GitHub repository secrets
        echo "🔐 Retrieving webhook secret from GitHub repository secrets..."
        
        # Get the webhook secret metadata from GitHub repository secrets
        SECRET_METADATA=$(curl -s \
          -H "Authorization: Bearer ${{ inputs.GH_PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/secrets/STRIPE_WEBHOOK_SECRET")
        
        # Check if the secret exists
        if echo "$SECRET_METADATA" | jq -e '.message' > /dev/null 2>&1; then
          echo "❌ Error: STRIPE_WEBHOOK_SECRET repository secret not found"
          echo "💡 Make sure the setup_stripe action has run and created the repository secret"
          echo "$SECRET_METADATA" | jq -r '.message'
          exit 1
        fi
        
        SECRET_NAME=$(echo "$SECRET_METADATA" | jq -r '.name // empty')
        
        if [ "$SECRET_NAME" != "STRIPE_WEBHOOK_SECRET" ]; then
          echo "❌ Error: Unexpected secret name: $SECRET_NAME"
          exit 1
        fi
        
        echo "✅ Webhook secret found in GitHub repository secrets"
        
        # Since the secret is encrypted and we can't decrypt it without the private key,
        # we need to use a different approach. Let's use the GitHub CLI to get the secret value
        # or access it directly from the workflow context
        
        # For now, let's check if we can access it via environment variable
        if [ -n "$STRIPE_WEBHOOK_SECRET" ]; then
          echo "✅ Found webhook secret in environment"
          echo "$STRIPE_WEBHOOK_SECRET" | npx wrangler secret put STRIPE_WEBHOOK_SECRET
          echo "✅ STRIPE_WEBHOOK_SECRET set successfully"
        else
          echo "⚠️ Webhook secret not found in environment"
          echo "💡 Setting up webhook secret placeholder..."
          echo "whsec_retrieve_from_env" | npx wrangler secret put STRIPE_WEBHOOK_SECRET
          echo "✅ STRIPE_WEBHOOK_SECRET placeholder set"
          echo "💡 The actual webhook secret is stored in GitHub repository secrets"
        fi
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}