name: 'Deploy Auth Service'
description: 'Deploys the auth service'

inputs:
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: './auth-service'
      shell: bash
      run: 'npm install'

    # There is a bug in the cloudflare terraform provider. We will have to reupload an ES module worker
    # using the API after our terraform run has completed.
    - name: Deploy Worker
      working-directory: './auth-service'
      shell: bash
      run: 'npx wrangler deploy'
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}