name: 'Terraform Init'
description: 'Initialize Terraform working directory'

runs:
  using: "composite"
  steps:
    - name: Init
      shell: bash
      working-directory: ./terraform
      run: |
        terraform init -upgrade 