name: 'Terraform Init'
description: 'Initialize Terraform working directory'

inputs:
  GH_PERSONAL_ACCESS_TOKEN:
    description: 'GitHub token for pushing changes'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch existing Terraform files
      shell: bash
      run: |
        git fetch origin main
        git checkout origin/main -- terraform/ || true

    - name: Terraform Init
      shell: bash
      working-directory: ./terraform
      run: |
        terraform init -upgrade 

    - name: Check for Terraform files changes
      id: check_terraform_files
      shell: bash
      run: |
        git fetch origin main
        if git diff origin/main -- terraform/.terraform terraform/.terraform.lock.hcl | grep .; then
          echo "changes=true" >> $GITHUB_ENV
          echo "env.changes is: ${{ env.changes }}"
        else
          echo "changes=false" >> $GITHUB_ENV
          echo "env.changes is: ${{ env.changes }}"
        fi

    - name: Print changes env var
      shell: bash
      run: |
        echo "env.changes is: ${{ env.changes }}"

    - name: Commit Terraform files
      if: env.changes == 'true'
      shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add terraform/.terraform terraform/.terraform.lock.hcl
        git commit -m "Save Result of Terraform Init"

    - name: Push Terraform files
      if: env.changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ inputs.GH_PERSONAL_ACCESS_TOKEN }}
        branch: main 