name: 'Terraform Apply'
description: 'Apply Terraform configuration'

inputs:
  domain:
    description: 'Domain name for the deployment'
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Apply
      shell: bash
      working-directory: ./terraform
      run: |
        terraform apply -auto-approve 
      env:
        TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}