name: 'Deploy Frontend'
description: 'Deploys the frontend application to the target environment'

inputs:
  domain:
    description: 'Domain Name'
    required: true
  droplet_ip:
    description: 'Digital Ocean Droplet IP'
    required: true
  GH_PERSONAL_ACCESS_TOKEN:
    description: 'GitHub Personal Access Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Frontend Artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/