name = "auth-service"
main = "src/worker.ts"
compatibility_date = "2025-06-14"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "auth_db"
database_id = "YOUR_DB_ID"  # You'll need to replace this with your actual database ID