name: 'Deploy Frontend'
description: 'Deploys the Vite application to the target environment'

inputs:
  domain:
    description: 'Domain Name'
    required: true
  droplet_ip:
    description: 'Digital Ocean Droplet IP'
    required: true
  DIGITAL_OCEAN_SSH_PRIVATE_KEY:
    description: 'Digital Ocean SSH Private Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}

    - name: Prepare server
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ inputs.droplet_ip }} "
          rm -rf /var/www/${{ inputs.domain }}/*
          mkdir -p /var/www/${{ inputs.domain }}
        "

    - name: Deploy Vite build
      shell: bash
      run: |
        scp -o StrictHostKeyChecking=no -r ./dist/* root@${{ inputs.droplet_ip }}:/var/www/${{ inputs.domain }}/

    - name: Validate Deployment
      shell: bash
      run: |
        # Count files in local build
        local_files=$(find ./dist -type f | wc -l)
        
        # Count files on remote server
        remote_files=$(ssh -o StrictHostKeyChecking=no root@${{ inputs.droplet_ip }} "find /var/www/${{ inputs.domain }} -type f | wc -l")
        
        # Check if directory exists and has files
        if [ "$remote_files" -eq 0 ]; then
          echo "Error: No files found in remote directory"
          exit 1
        fi
        
        # Compare file counts (allowing for some difference due to potential hidden files)
        if [ "$remote_files" -lt "$((local_files * 9 / 10))" ]; then
          echo "Error: Remote directory has significantly fewer files than local build"
          echo "Local files: $local_files"
          echo "Remote files: $remote_files"
          exit 1
        fi
        
        echo "✅ Vite application deployed successfully"