name: Validate AWS Access
description: Validate that the AWS credentials are present in the repository secrets and variables

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check AWS Access Key ID
      shell: bash
      run: |
        if [ -z "${{ inputs.aws_access_key_id }}" ]; then
          echo "::error::AWS Access Key ID is missing. Please add it to your repository secrets:"
          echo "1. Go to your repository settings"
          echo "2. Navigate to Secrets and Variables > Actions"
          echo "3. Click 'New repository secret'"§
          echo "4. Name: AWS_ACCESS_KEY_ID"
          echo "5. Value: Your AWS Access Key ID"
          echo "6. Click 'Add secret'"
          exit 1
        fi
        echo "✅ AWS Access Key ID is present"
    
    - name: Check AWS Secret Access Key
      shell: bash
      run: |
        if [ -z "${{ inputs.aws_secret_access_key }}" ]; then
          echo "::error::AWS Secret Access Key is missing. Please add it to your repository secrets:"
          echo "1. Go to your repository settings"
          echo "2. Navigate to Secrets and Variables > Actions"
          echo "3. Click 'New repository secret'"
          echo "4. Name: AWS_SECRET_ACCESS_KEY"
          echo "5. Value: Your AWS Secret Access Key"
          echo "6. Click 'Add secret'"
          exit 1
        fi
        echo "✅ AWS Secret Access Key is present"

    