name: 'Setup Brevo Domain Authentication'
description: 'Automatically sets up domain authentication in Brevo for multiple domains'

inputs:
  brevo_api_key:
    description: 'Brevo API key for domain management'
    required: true
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get domains from R2
      id: get-domains
      shell: bash
      run: |
        echo "Retrieving domains from R2..."
        
        # Get domain mappings from R2
        MAPPINGS_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/r2/buckets/domain-mappings/objects/mappings.json" \
          -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
          -H "Content-Type: application/json")
        
        echo "Raw response from R2:"
        echo "$MAPPINGS_RESPONSE"
        
        # Check if we got a valid response
        if ! echo "$MAPPINGS_RESPONSE" | jq empty 2>/dev/null; then
          echo "::error::Failed to retrieve domain mappings from R2 - invalid JSON"
          echo "$MAPPINGS_RESPONSE"
          exit 1
        fi
        
        # Check if response is an array (success case) or has errors
        if echo "$MAPPINGS_RESPONSE" | jq -e 'type == "array"' > /dev/null; then
          # Response is an array, which is what we expect
          echo "✅ Successfully retrieved domain mappings from R2"
        elif echo "$MAPPINGS_RESPONSE" | jq -e '.errors' > /dev/null; then
          # Response has errors
          echo "::error::Failed to get domain mappings"
          echo "$MAPPINGS_RESPONSE" | jq -r '.errors[0].message'
          exit 1
        else
          echo "::error::Unexpected response format from R2"
          echo "$MAPPINGS_RESPONSE"
          exit 1
        fi
        
        # Store the domains as a single line JSON string
        echo "domains=$(echo "$MAPPINGS_RESPONSE" | jq -c '.')" >> $GITHUB_OUTPUT
        echo "Retrieved $(echo "$MAPPINGS_RESPONSE" | jq '. | length') domains from R2"

    - name: Process domains for Brevo authentication
      shell: bash
      run: |
        echo "Processing domains for Brevo authentication..."
        
        # Get the domains from the previous step
        DOMAINS='${{ steps.get-domains.outputs.domains }}'
        
        echo "Domains from step output: $DOMAINS"
        
        # Check if domains list is empty or null
        if [ "$DOMAINS" = "[]" ] || [ "$DOMAINS" = "null" ] || [ -z "$DOMAINS" ]; then
          echo "No domains found, skipping Brevo authentication setup"
          exit 0
        fi
        
        # Validate that domains is a valid JSON array
        if ! echo "$DOMAINS" | jq -e 'type == "array"' > /dev/null; then
          echo "::error::Invalid domains format - expected JSON array"
          echo "Domains: $DOMAINS"
          exit 1
        fi
        
        # Process each domain
        echo "$DOMAINS" | jq -c '.[]' | while read -r domain_obj; do
          DOMAIN=$(echo "$domain_obj" | jq -r '.domain')
          echo "Processing domain: $DOMAIN"
          
          # Step 1: Check if domain already exists in Brevo
          echo "Step 1: Checking if domain exists..."
          DOMAIN_RESPONSE=$(curl -s -X GET "https://api.brevo.com/v3/senders/domains" \
            -H "accept: application/json" \
            -H "api-key: ${{ inputs.brevo_api_key }}")
          
          # Check if the response is valid JSON
          if ! echo "$DOMAIN_RESPONSE" | jq empty 2>/dev/null; then
            echo "❌ Invalid JSON response from Brevo API"
            echo "$DOMAIN_RESPONSE"
            continue
          fi
          
          # Check if the response has the expected structure
          if ! echo "$DOMAIN_RESPONSE" | jq -e '.domains' > /dev/null 2>&1; then
            echo "❌ Unexpected response structure from Brevo API"
            echo "$DOMAIN_RESPONSE"
            continue
          fi
          
          DOMAIN_ID=$(echo "$DOMAIN_RESPONSE" | jq -r ".domains[] | select(.domain_name == \"$DOMAIN\") | .id // empty")
          
          if [ "$DOMAIN_ID" != "null" ] && [ -n "$DOMAIN_ID" ]; then
            echo "✅ Domain $DOMAIN already exists in Brevo with ID: $DOMAIN_ID"
            # Get full domain details using individual domain endpoint
            DOMAIN_DETAILS=$(curl -s -X GET "https://api.brevo.com/v3/senders/domains/$DOMAIN" \
              -H "accept: application/json" \
              -H "api-key: ${{ inputs.brevo_api_key }}")
          else
            # Creating domain if it doesn't exist
            echo "Creating domain..."
            echo "Adding domain $DOMAIN to Brevo..."
            
            # Add domain to Brevo
            DOMAIN_ADD_RESPONSE=$(curl -s -X POST "https://api.brevo.com/v3/senders/domains" \
              -H "accept: application/json" \
              -H "content-type: application/json" \
              -H "api-key: ${{ inputs.brevo_api_key }}" \
              -d "{\"name\":\"$DOMAIN\"}")
            
            if echo "$DOMAIN_ADD_RESPONSE" | jq -e '.id' > /dev/null 2>&1; then
              DOMAIN_ID=$(echo "$DOMAIN_ADD_RESPONSE" | jq -r '.id')
              echo "✅ Domain $DOMAIN added to Brevo with ID: $DOMAIN_ID"
              # Use domain details from the creation response
              DOMAIN_DETAILS="$DOMAIN_ADD_RESPONSE"
            else
              ERROR_MSG=$(echo "$DOMAIN_ADD_RESPONSE" | jq -r '.message // "Unknown error"')
              echo "❌ Failed to add domain $DOMAIN to Brevo: $ERROR_MSG"
              continue
            fi
          fi
          
          # Step 2: Add DNS records to Cloudflare
          echo "Step 2: Adding DNS records to Cloudflare..."
          
          # Debug: Print domain details to understand the structure
          echo "DEBUG: Domain details from Brevo:"
          echo "$DOMAIN_DETAILS" | jq '.'
          
          # Get zone ID for the domain
          ZONE_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -H "Content-Type: application/json")
          
          ZONE_ID=$(echo "$ZONE_RESPONSE" | jq -r '.result[0].id')
          
          if [ "$ZONE_ID" != "null" ] && [ -n "$ZONE_ID" ]; then
            # Add DKIM record - handle both response formats
            DKIM_RECORD=$(echo "$DOMAIN_DETAILS" | jq -r '.dns_records.dkim_record.host_name // .dns_records.dkim1Record.host_name // empty')
            DKIM_VALUE=$(echo "$DOMAIN_DETAILS" | jq -r '.dns_records.dkim_record.value // .dns_records.dkim1Record.value // empty')
            
            echo "DEBUG: DKIM Record - Host: '$DKIM_RECORD', Value: '$DKIM_VALUE'"
            
            if [ "$DKIM_RECORD" != "null" ] && [ -n "$DKIM_RECORD" ] && [ "$DKIM_RECORD" != "" ] && [ "$DKIM_VALUE" != "null" ] && [ -n "$DKIM_VALUE" ]; then
              echo "Adding DKIM record: $DKIM_RECORD -> $DKIM_VALUE"
              
              # Check if DKIM record already exists
              EXISTING_DKIM=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?name=$DKIM_RECORD&type=CNAME" \
                -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
                -H "Content-Type: application/json")
              
              if echo "$EXISTING_DKIM" | jq -e '.result[] | select(.content == "'$DKIM_VALUE'")' > /dev/null 2>&1; then
                echo "✅ DKIM record already exists for $DOMAIN"
              else
                # Add DKIM record
                DKIM_ADD_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
                  -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
                  -H "Content-Type: application/json" \
                  -d "{
                    \"type\": \"CNAME\",
                    \"name\": \"$DKIM_RECORD\",
                    \"content\": \"$DKIM_VALUE\",
                    \"ttl\": 1
                  }")
                
                if echo "$DKIM_ADD_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
                  echo "✅ DKIM record added for $DOMAIN"
                else
                  ERROR_MSG=$(echo "$DKIM_ADD_RESPONSE" | jq -r '.errors[0].message // "Unknown error"')
                  if [[ "$ERROR_MSG" == *"already exists"* ]]; then
                    echo "✅ DKIM record already exists for $DOMAIN (detected via error)"
                  else
                    echo "❌ Failed to add DKIM record for $DOMAIN: $ERROR_MSG"
                  fi
                fi
              fi
            else
              echo "⚠️ No valid DKIM record found for domain $DOMAIN"
              echo "DEBUG: DKIM_RECORD='$DKIM_RECORD', DKIM_VALUE='$DKIM_VALUE'"
            fi
            
            # Add Brevo code record - handle both response formats
            BREVO_CODE_HOST=$(echo "$DOMAIN_DETAILS" | jq -r '.dns_records.brevo_code.host_name // empty')
            BREVO_CODE_VALUE=$(echo "$DOMAIN_DETAILS" | jq -r '.dns_records.brevo_code.value // empty')
            
            echo "DEBUG: Brevo Code Record - Host: '$BREVO_CODE_HOST', Value: '$BREVO_CODE_VALUE'"
            
            if [ "$BREVO_CODE_HOST" != "null" ] && [ -n "$BREVO_CODE_HOST" ] && [ "$BREVO_CODE_HOST" != "" ] && [ "$BREVO_CODE_VALUE" != "null" ] && [ -n "$BREVO_CODE_VALUE" ]; then
              echo "Adding Brevo code record: $BREVO_CODE_HOST -> $BREVO_CODE_VALUE"
              
              # Check if Brevo code record already exists
              EXISTING_BREVO_CODE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?name=$BREVO_CODE_HOST&type=TXT" \
                -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
                -H "Content-Type: application/json")
              
              if echo "$EXISTING_BREVO_CODE" | jq -e '.result[] | select(.content == "'$BREVO_CODE_VALUE'")' > /dev/null 2>&1; then
                echo "✅ Brevo code record already exists for $DOMAIN"
              else
                # Add Brevo code record
                BREVO_CODE_ADD_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
                  -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
                  -H "Content-Type: application/json" \
                  -d "{
                    \"type\": \"TXT\",
                    \"name\": \"$BREVO_CODE_HOST\",
                    \"content\": \"$BREVO_CODE_VALUE\",
                    \"ttl\": 1
                  }")
                
                if echo "$BREVO_CODE_ADD_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
                  echo "✅ Brevo code record added for $DOMAIN"
                else
                  ERROR_MSG=$(echo "$BREVO_CODE_ADD_RESPONSE" | jq -r '.errors[0].message // "Unknown error"')
                  if [[ "$ERROR_MSG" == *"already exists"* ]]; then
                    echo "✅ Brevo code record already exists for $DOMAIN (detected via error)"
                  else
                    echo "❌ Failed to add Brevo code record for $DOMAIN: $ERROR_MSG"
                  fi
                fi
              fi
            else
              echo "⚠️ No valid Brevo code record found for domain $DOMAIN"
              echo "DEBUG: BREVO_CODE_HOST='$BREVO_CODE_HOST', BREVO_CODE_VALUE='$BREVO_CODE_VALUE'"
            fi
          else
            echo "❌ Zone not found for domain $DOMAIN"
          fi
          
          # Step 3: Wait for DNS propagation (after adding records)
          echo "Step 3: Waiting for DNS propagation..."
          
          # Debug: Print the hostnames we'll be checking
          echo "DEBUG: Will check DNS propagation for:"
          echo "  - SPF: $DOMAIN"
          echo "  - Brevo Code: $BREVO_CODE_HOST"
          echo "  - DKIM: $DKIM_RECORD"
          
          # Check if we have all required hostnames to validate
          VALID_HOSTNAMES=0
          MISSING_HOSTNAMES=""
          
          if [ "$BREVO_CODE_HOST" != "null" ] && [ -n "$BREVO_CODE_HOST" ] && [ "$BREVO_CODE_HOST" != "" ]; then
            VALID_HOSTNAMES=$((VALID_HOSTNAMES + 1))
          else
            MISSING_HOSTNAMES="$MISSING_HOSTNAMES Brevo code"
          fi
          
          if [ "$DKIM_RECORD" != "null" ] && [ -n "$DKIM_RECORD" ] && [ "$DKIM_RECORD" != "" ]; then
            VALID_HOSTNAMES=$((VALID_HOSTNAMES + 1))
          else
            MISSING_HOSTNAMES="$MISSING_HOSTNAMES DKIM"
          fi
          
          if [ $VALID_HOSTNAMES -lt 2 ]; then
            echo "::error::Missing required DNS record hostnames for domain $DOMAIN: $MISSING_HOSTNAMES"
            echo "DEBUG: BREVO_CODE_HOST='$BREVO_CODE_HOST', DKIM_RECORD='$DKIM_RECORD'"
            echo "Cannot proceed with DNS validation without all required hostnames"
            exit 1
          fi
          
          echo "DEBUG: Found all required hostnames ($VALID_HOSTNAMES/2)"
          
          # Wait for DNS propagation (up to 10 minutes)
          for i in {1..60}; do
            echo "Checking DNS propagation (attempt $i/60)..."
            
            # Check if SPF record is available
            SPF_CHECK=$(dig TXT @8.8.8.8 "$DOMAIN" +short | grep "v=spf1" || echo "")
            
            # Check if Brevo code record is available (hostname already validated above)
            # Handle @ symbol for root domain
            if [ "$BREVO_CODE_HOST" = "@" ]; then
              echo "DEBUG: Checking Brevo code record for root domain '$DOMAIN'"
              BREVO_CODE_CHECK=$(dig TXT @8.8.8.8 "$DOMAIN" +short | grep "brevo-code" || echo "")
            else
              echo "DEBUG: Checking Brevo code record for '$BREVO_CODE_HOST'"
              BREVO_CODE_CHECK=$(dig TXT @8.8.8.8 "$BREVO_CODE_HOST" +short | grep "brevo-code" || echo "")
            fi
            
            # Check if DKIM record is available (hostname already validated above)
            echo "DEBUG: Checking DKIM record for '$DKIM_RECORD'"
            DKIM_CHECK=$(dig CNAME @8.8.8.8 "$DKIM_RECORD" +short | grep "brevo" || echo "")
            
            echo "SPF available: $([ -n "$SPF_CHECK" ] && echo "✅" || echo "❌")"
            echo "Brevo code available: $([ -n "$BREVO_CODE_CHECK" ] && echo "✅" || echo "❌")"
            echo "DKIM available: $([ -n "$DKIM_CHECK" ] && echo "✅" || echo "❌")"
            
            # Check all required records (SPF + Brevo code + DKIM)
            VALID_CHECKS=0
            TOTAL_CHECKS=3
            
            if [ -n "$SPF_CHECK" ]; then
              VALID_CHECKS=$((VALID_CHECKS + 1))
            fi
            if [ -n "$BREVO_CODE_CHECK" ]; then
              VALID_CHECKS=$((VALID_CHECKS + 1))
            fi
            if [ -n "$DKIM_CHECK" ]; then
              VALID_CHECKS=$((VALID_CHECKS + 1))
            fi
            
            echo "DEBUG: Valid checks: $VALID_CHECKS/$TOTAL_CHECKS"
            
            if [ $VALID_CHECKS -eq $TOTAL_CHECKS ]; then
              echo "✅ DNS propagation complete for $DOMAIN"
              break
            elif [ $i -eq 60 ]; then
              echo "❌ DNS propagation timeout after 10 minutes for domain $DOMAIN"
              echo "SPF available: $([ -n "$SPF_CHECK" ] && echo "✅" || echo "❌")"
              echo "Brevo code available: $([ -n "$BREVO_CODE_CHECK" ] && echo "✅" || echo "❌")"
              echo "DKIM available: $([ -n "$DKIM_CHECK" ] && echo "✅" || echo "❌")"
              echo "::warning::DNS propagation failed for domain $DOMAIN after 10 minutes, but continuing..."
            else
              sleep 10
            fi
          done
          
          # Step 4: Authenticate domain
          echo "Step 4: Authenticating domain..."
          AUTH_RESPONSE=$(curl -s -X PUT "https://api.brevo.com/v3/senders/domains/$DOMAIN/authenticate" \
            -H "accept: application/json" \
            -H "api-key: ${{ inputs.brevo_api_key }}")
          
          if echo "$AUTH_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
            echo "✅ Domain authentication triggered for $DOMAIN"
          else
            echo "⚠️ Failed to trigger domain authentication for $DOMAIN (may already be authenticated)"
            echo "$AUTH_RESPONSE"
          fi
          
          # Add sender to Brevo (regardless of domain existence)
          echo "Adding sender noreply@$DOMAIN to Brevo..."
          
          # Check if sender already exists
          SENDER_RESPONSE=$(curl -s -X GET "https://api.brevo.com/v3/senders" \
            -H "accept: application/json" \
            -H "api-key: ${{ inputs.brevo_api_key }}")
          
          echo "Brevo senders response:"
          echo "$SENDER_RESPONSE"
          
          # Check if the response is valid JSON
          if ! echo "$SENDER_RESPONSE" | jq empty 2>/dev/null; then
            echo "❌ Invalid JSON response from Brevo senders API"
            echo "$SENDER_RESPONSE"
            continue
          fi
          
          # Check if the response has the expected structure
          if ! echo "$SENDER_RESPONSE" | jq -e '.senders' > /dev/null 2>&1; then
            echo "❌ Unexpected response structure from Brevo senders API"
            echo "$SENDER_RESPONSE"
            continue
          fi
          
          if echo "$SENDER_RESPONSE" | jq -e ".senders[] | select(.email == \"noreply@$DOMAIN\")" > /dev/null 2>&1; then
            echo "✅ Sender noreply@$DOMAIN already exists in Brevo"
          else
            # Add sender
            SENDER_ADD_RESPONSE=$(curl -s -X POST "https://api.brevo.com/v3/senders" \
              -H "accept: application/json" \
              -H "content-type: application/json" \
              -H "api-key: ${{ inputs.brevo_api_key }}" \
              -d "{
                \"email\": \"noreply@$DOMAIN\",
                \"name\": \"$DOMAIN\"
              }")
            
            if echo "$SENDER_ADD_RESPONSE" | jq -e '.id' > /dev/null 2>&1; then
              echo "✅ Sender noreply@$DOMAIN added to Brevo"
            else
              ERROR_MSG=$(echo "$SENDER_ADD_RESPONSE" | jq -r '.message // "Unknown error"')
              echo "❌ Failed to add sender noreply@$DOMAIN: $ERROR_MSG"
            fi
          fi
          
          echo "---"
        done
        
        echo "✅ Brevo domain authentication setup completed for all domains" 