name: 'Configure Nginx'
description: 'Configures Nginx for the deployment'

inputs:
  droplet_ip:
    description: 'Digital Ocean Droplet IP'
    required: true
  digital_ocean_ssh_private_key:
    description: 'SSH private key for DigitalOcean'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.digital_ocean_ssh_private_key }}

    - name: Configure Nginx
      shell: bash
      run: |
        DROPLET_IP="${{ inputs.droplet_ip }}"
        echo "Configuring Nginx..."
        
        # Read domains from domains.txt
        DOMAINS=$(cat domains.txt)
        
        # Create the final nginx configuration
        for domain in $DOMAINS; do
          if [ -n "$domain" ]; then
            sed "s/{{domain}}/$domain/g" nginx/domain.conf.template >> nginx.conf
          fi
        done
        
        # Upload the configuration to the droplet
        scp -o StrictHostKeyChecking=no nginx.conf deploy@$DROPLET_IP:/tmp/nginx.conf
        
        # Move configuration to the correct location and set permissions
        ssh -o StrictHostKeyChecking=no deploy@$DROPLET_IP "sudo mv /tmp/nginx.conf /etc/nginx/nginx.conf && \
          sudo chown root:root /etc/nginx/nginx.conf && \
          sudo chmod 644 /etc/nginx/nginx.conf"
        
        # Test and reload Nginx configuration
        ssh -o StrictHostKeyChecking=no deploy@$DROPLET_IP "sudo nginx -t && sudo systemctl reload nginx" 