name: 'Terraform Plan'
description: 'Create Terraform execution plan'

inputs:
  working-directory:
    description: 'Working directory for Terraform'
    required: true
  domain:
    description: 'Domain name for the deployment'
    required: true
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API Token'
    required: true

outputs:
  terraform_error:
    description: 'Whether there was a terraform error'
    value: ${{ steps.terraform.outputs.terraform_error }}

runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      id: terraform
      shell: bash
      working-directory: ./terraform
      run: |
        set +e
        timeout 900 terraform plan -out=tfplan
        exit_code=$?
        if [ $exit_code -eq 124 ]; then
          echo "::error::Terraform plan timed out after 15 minutes"
          echo "terraform_error=true" >> $GITHUB_OUTPUT
          exit 1
        elif [ $exit_code -ne 0 ]; then
          echo "terraform_error=true" >> $GITHUB_OUTPUT
        else
          echo "terraform_error=false" >> $GITHUB_OUTPUT
        fi
        exit $exit_code
      env:
        TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        TF_VAR_CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        TF_LOG: DEBUG