name: 'Build Auth Service'
description: 'Builds the auth service'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v4'

    - name: 'Setup Node.js'
      uses: 'actions/setup-node@v4'
      with:
        node-version: '20'

    - name: 'Install dependencies'
      working-directory: './auth-service'
      shell: bash
      run: 'npm install'

    - name: 'Build'
      working-directory: './auth-service'
      shell: bash
      run: 'npx wrangler build'

    - name: 'Upload artifact'
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'auth-service'
        path: 'auth-service/.wrangler'
        retention-days: 1