name: 'Validate Stripe Credentials'
description: 'Validates Stripe API credentials by testing the connection'

inputs:
  stripe_secret_key:
    description: 'Stripe secret key to validate'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Stripe
      shell: bash
      run: 'npm install stripe'

    - name: Validate Stripe Secret Key
      shell: bash
      run: |
        node -e "
        const Stripe = require('stripe');
        const stripe = new Stripe('${{ inputs.stripe_secret_key }}', {
          apiVersion: '2023-10-16'
        });
        
        stripe.customers.list({ limit: 1 })
          .then(() => {
            console.log('✅ Stripe secret key is valid');
            process.exit(0);
          })
          .catch((error) => {
            console.error('❌ Stripe secret key validation failed:', error.message);
            process.exit(1);
          });
        " 