name: 'Build Frontend'
description: 'Builds the frontend application using Vite'

inputs:
  frontend_repo:
    description: 'Frontend Repository URL (e.g., https://github.com/username/repo)'
    required: true
  GH_PERSONAL_ACCESS_TOKEN:
    description: 'GitHub Personal Access Token'
    required: true

outputs:
  artifact_path:
    description: 'Path to the built frontend artifacts'
    value: ${{ steps.build.outputs.artifact_path }}

runs:
  using: "composite"
  steps:
    - name: Extract repository name
      id: extract_repo
      shell: bash
      run: |
        if [[ "${{ inputs.frontend_repo }}" == https://github.com/* ]]; then
          echo "repo=$(echo "${{ inputs.frontend_repo }}" | sed 's|https://github.com/||')" >> $GITHUB_OUTPUT
        else
          echo "repo=${{ inputs.frontend_repo }}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout frontend repository
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.extract_repo.outputs.repo }}
        token: ${{ inputs.GH_PERSONAL_ACCESS_TOKEN }}
        path: frontend

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      working-directory: frontend
      run: npm ci

    - name: Build
      id: build
      shell: bash
      working-directory: frontend
      run: |
        npm run build -- --mode production
        echo "artifact_path=frontend/dist/" >> $GITHUB_OUTPUT

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/
        retention-days: 1 