name: 'Validate Digital Ocean SSH Keys'
description: 'Validate that the Digital Ocean SSH keys are present in the repository secrets and variables'

inputs:
  digitalocean_ssh_private_key:
    description: 'Digital Ocean SSH Private Key'
    required: true
  digitalocean_ssh_key_name:
    description: 'Digital Ocean SSH Key Name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Digital Ocean SSH Private Key
      shell: bash
      run: |
        if [ -z "${{ inputs.digitalocean_ssh_private_key }}" ]; then
          echo "::error::Digital Ocean SSH Private Key is missing"
          echo ""
          echo "Please add your SSH private key to your repository secrets:"
          echo "1. Go to your repository settings"
          echo "2. Navigate to Secrets and Variables > Actions"
          echo "3. Click 'New repository secret'"
          echo "4. Name: DIGITALOCEAN_SSH_PRIVATE_KEY"
          echo "5. Value: Your SSH private key content"
          echo "6. Click 'Add secret'"
          exit 1
        fi
        echo "✅ Digital Ocean SSH Private Key is present"

    - name: Check Digital Ocean SSH Key Name
      shell: bash
      run: |
        if [ -z "${{ inputs.digitalocean_ssh_key_name }}" ]; then
          echo "::error::Digital Ocean SSH Key Name is missing"
          echo ""
          echo "Please add your SSH key name to your repository secrets:"
          echo "1. Go to your repository settings"
          echo "2. Navigate to Secrets and Variables > Actions"
          echo "3. Click 'New repository secret'"
          echo "4. Name: DIGITAL_OCEAN_SSH_KEY_NAME"
          echo "5. Value: Your SSH key name"
          echo "6. Click 'Add secret'"
          exit 1
        fi
        echo "✅ Digital Ocean SSH Key Name is present" 