name: 'Deploy Pages'
description: 'Deploys all Cloudflare Pages projects'

inputs:
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true
  cloudflare_email:
    description: 'Cloudflare email'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y jq
        fi

    - name: Get Domain Mappings from R2
      id: get-mappings
      shell: bash
      run: |
        # Get domain mappings from R2
        MAPPINGS_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/r2/buckets/domain-mappings/objects/mappings.json" \
          -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
          -H "Content-Type: application/json")
        
        # Check if we got a valid response and if the file exists
        if echo "$MAPPINGS_RESPONSE" | jq -e '.success == false and .errors[0].code == 10007' > /dev/null; then
          # File doesn't exist, start with empty array
          echo "No existing mappings file found, starting fresh"
          MAPPINGS='[]'
        elif echo "$MAPPINGS_RESPONSE" | jq -e '.success == true' > /dev/null; then
          # File exists and is valid JSON, extract the result
          MAPPINGS=$(echo "$MAPPINGS_RESPONSE" | jq -c '.result')
        else
          echo "::error::Invalid response from R2"
          echo "$MAPPINGS_RESPONSE"
          exit 1
        fi
        
        # Store the mappings as a single line JSON string
        echo "mappings=$MAPPINGS" >> $GITHUB_OUTPUT

    - name: Create Deployments
      shell: bash
      run: |
        # Extract project names and domains from mappings
        MAPPINGS='${{ steps.get-mappings.outputs.mappings }}'
        if [ "$MAPPINGS" = "[]" ]; then
          echo "No domain mappings found, skipping deployments"
          exit 0
        fi
        
        # Create a map of project names to their domains and price IDs
        PROJECT_DOMAIN_MAP=$(echo "$MAPPINGS" | jq -r '.[] | "\(.frontend_repo | split("/") | last):\(.domain):\(.stripe_price_id // "")"')
        
        # Deploy each project only if there are new commits
        while IFS=: read -r project domain price_id; do
          echo "Checking for new commits in project: $project (domain: $domain)"
          
          # Get the latest deployment to check if we need to deploy
          latest_deployment=$(curl -s "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments?per_page=1" \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -H "Content-Type: application/json")
          
          if ! echo "$latest_deployment" | jq -e '.success == true' > /dev/null; then
            echo "::error::Failed to get latest deployment for project $project"
            echo "$latest_deployment" | jq -r '.errors[0].message'
            exit 1
          fi
          
          # Get the commit hash of the latest deployment
          latest_commit=$(echo "$latest_deployment" | jq -r '.result[0].deployment_trigger.metadata.commit_hash // empty')
          
          # Get the current commit hash from the main branch
          current_commit=$(curl -s "https://api.github.com/repos/${{ github.repository_owner }}/$project/commits/main" \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" | jq -r '.sha')
          
          if [ "$latest_commit" = "$current_commit" ]; then
            echo "No new commits for project $project, skipping deployment"
            continue
          fi
          
          echo "New commits detected for project $project, triggering deployment"
          echo "Contacting ... https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments"
          
          # Trigger deployment
          response=$(curl -s https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -d '{"branch": "main"}')
          
          # Check if the request was successful
          if ! echo "$response" | jq -e '.success == true' > /dev/null; then
            echo "::error::Failed to deploy project $project"
            echo "$response" | jq -r '.errors[0].message'
            exit 1
          fi
          
          echo "Successfully triggered deployment for project $project"
        done <<< "$PROJECT_DOMAIN_MAP"

    - name: Configure Custom Domains
      shell: bash
      run: |
        # Extract project names and domains from mappings
        MAPPINGS='${{ steps.get-mappings.outputs.mappings }}'
        if [ "$MAPPINGS" = "[]" ]; then
          echo "No domain mappings found, skipping domain configuration"
          exit 0
        fi
        
        PROJECTS=$(echo "$MAPPINGS" | jq -r '.[].frontend_repo | split("/") | last')
        DOMAINS=$(echo "$MAPPINGS" | jq -r '.[].domain')
        
        # Convert to arrays
        readarray -t project_array <<< "$PROJECTS"
        readarray -t domain_array <<< "$DOMAINS"
        
        # Configure custom domain for each project
        for i in "${!project_array[@]}"; do
          project="${project_array[$i]}"
          domain="${domain_array[$i]}"
          echo "Contacting ... https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/domains"
          response=$(curl -s https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/domains \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -d "{\"name\": \"$domain\"}")
          
          # Check if the request was successful or if domain is already configured
          if ! echo "$response" | jq -e '.success == true' > /dev/null; then
            error_message=$(echo "$response" | jq -r '.errors[0].message')
            if [[ "$error_message" == *"already added this custom domain"* ]]; then
              echo "Domain $domain is already configured for project $project"
            else
              echo "::error::Failed to configure domain $domain for project $project"
              echo "$error_message"
              exit 1
            fi
          fi
        done

    - name: Configure Environment Variables
      shell: bash
      run: |
        # Extract project names and domains from mappings
        MAPPINGS='${{ steps.get-mappings.outputs.mappings }}'
        if [ "$MAPPINGS" = "[]" ]; then
          echo "No domain mappings found, skipping environment variable configuration"
          exit 0
        fi
        
        # Create a map of project names to their domains and price IDs
        PROJECT_DOMAIN_MAP=$(echo "$MAPPINGS" | jq -r '.[] | "\(.frontend_repo | split("/") | last):\(.domain):\(.stripe_price_id // "")"')
        
        # Configure environment variables for each project
        while IFS=: read -r project domain price_id; do
          echo "Configuring environment variables for project: $project (domain: $domain)"
          
          if [ -n "$price_id" ] && [ "$price_id" != "null" ]; then
            echo "Using price ID for $domain: $price_id"
            # Use simple environment variable name since it's project-specific
            ENV_VAR_NAME="STRIPE_PRICE_ID"
            echo "Setting environment variable: $ENV_VAR_NAME"
            
            # Set the environment variable at the project level for production environment
            response=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/environments/production/variables/$ENV_VAR_NAME" \
              -H 'Content-Type: application/json' \
              -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
              -d "{\"value\": \"$price_id\"}")
            
            echo "API Response: $response"
            
            # Check if the request was successful
            if ! echo "$response" | jq -e '.success == true' > /dev/null; then
              error_message=$(echo "$response" | jq -r '.errors[0].message // "Unknown error"')
              if [[ "$error_message" == *"already exists"* ]]; then
                echo "Environment variable $ENV_VAR_NAME already exists for project $project"
              else
                echo "::error::Failed to set environment variable $ENV_VAR_NAME for project $project"
                echo "Error message: $error_message"
                echo "Full response: $response"
                exit 1
              fi
            else
              echo "Successfully set environment variable $ENV_VAR_NAME for project $project"
            fi
          else
            echo "No price ID found for $domain, skipping environment variable configuration"
          fi
        done <<< "$PROJECT_DOMAIN_MAP"