name: 'Deploy Pages'
description: 'Deploys all Cloudflare Pages projects'

inputs:
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true
  cloudflare_email:
    description: 'Cloudflare email'
    required: true
  projects:
    description: 'List of projects to deploy'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Deployments
      shell: bash
      run: |
        # Split projects string into array and deploy each project
        IFS=',' read -ra PROJECTS <<< "${{ inputs.projects }}"
        for project in "${PROJECTS[@]}"; do
          echo "Deploying project: $project"
          curl https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments \
            -H 'Content-Type: multipart/form-data' \
            -H "X-Auth-Email: ${{ inputs.cloudflare_email }}" \
            -H "X-Auth-Key: ${{ inputs.cloudflare_api_token }}" \
            -F branch=main
        done