name: 'Deploy Pages'
description: 'Deploys all Cloudflare Pages projects'

inputs:
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true
  cloudflare_email:
    description: 'Cloudflare email'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Deployments
      shell: bash
      run: |
        # Read domains.json and extract project names
        PROJECTS=$(jq -r '.[].frontend_repo | split("/") | last' domains.json)
        
        # Deploy each project
        for project in $PROJECTS; do
          echo "Contacting ... https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments"
          curl https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments \
            -H 'Content-Type: multipart/form-data' \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -F branch=main
        done