name: 'Deploy Pages'
description: 'Deploys all Cloudflare Pages projects'

inputs:
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare_api_token:
    description: 'Cloudflare API token'
    required: true
  cloudflare_email:
    description: 'Cloudflare email'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Deployments
      shell: bash
      run: |
        # Read domains.json and extract project names
        PROJECTS=$(jq -r '.[].frontend_repo | split("/") | last' domains.json)
        
        # Deploy each project
        for project in $PROJECTS; do
          echo "Contacting ... https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments"
          curl https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/deployments \
            -H 'Content-Type: multipart/form-data' \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -F branch=main
        done

    - name: Configure Custom Domains
      shell: bash
      run: |
        # Read domains.json and extract project names and domains
        PROJECTS=$(jq -r '.[].frontend_repo | split("/") | last' domains.json)
        DOMAINS=$(jq -r '.[].domain' domains.json)
        
        # Convert to arrays
        readarray -t project_array <<< "$PROJECTS"
        readarray -t domain_array <<< "$DOMAINS"
        
        # Configure custom domain for each project
        for i in "${!project_array[@]}"; do
          project="${project_array[$i]}"
          domain="${domain_array[$i]}"
          echo "Contacting ... https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/domains"
          curl https://api.cloudflare.com/client/v4/accounts/${{ inputs.cloudflare_account_id }}/pages/projects/$project/domains \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ inputs.cloudflare_api_token }}" \
            -d "{\"name\": \"$domain\"}"
        done