name = ""
main = "src/worker.ts"
compatibility_date = "2025-06-14"

[[d1_databases]]
# We define the binding here and not in the terraform config
# because there is a bug in the terraform provider relating to
# creating module workers (needed to bind to a D1 database).
binding = "DOMAIN_DB"
database_name = ""
database_id = ""

[[services]]
# Worker-to-worker binding to the auth service
binding = "AUTH_SERVICE"
service = ""