name: Build Frontend
description: 'Builds the frontend application'

on:
  workflow_call:
    inputs:
      frontend_repo:
        description: 'Frontend Repository URL (e.g., https://github.com/username/repo)'
        required: true
        type: string
    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.build.outputs.artifact_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Frontend
        id: build
        uses: ./.github/actions/build-frontend
        with:
          frontend_repo: ${{ inputs.frontend_repo }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 