name: Validate Cloudflare
description: 'Checks that the domain is using Cloudflare nameservers and that the cloudflare credentials are present in the repo secrets and variables'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string
  workflow_call:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  check-nameservers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Cloudflare nameservers
        uses: ./.github/actions/check_cloudflare_nameservers
        with:
          domain: ${{ inputs.domain }}
          
  validate-cloudflare-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Github Secrets
        uses: ./.github/actions/validate_cloudflare_credentials
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    # TODO: Add actions to create DNS records, load balancer, VM, HTTPS
    # Ensure we can reuse the same VM and load balancer for multiple domains

