name: Deploy Infrastructure
description: 'Deploys the project architecture if not already deployed'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string

jobs:
  cloudflare:
    name: 'Validate Cloudflare'
    uses: ./.github/workflows/cloudflare_validation.yaml
    with:
      domain: ${{ inputs.domain }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  terraform-init:
    needs: cloudflare
    uses: ./.github/workflows/terraform_init.yaml
    with:
      domain: ${{ inputs.domain }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}