name: Deploy Frontend
description: 'Deploys the frontend application to the target environment'

on:
  workflow_call:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string
      artifact_path:
        description: 'Path to the built frontend artifacts'
        required: true
        type: string
      droplet_ip:
        description: 'Digital Ocean Droplet IP'
        required: true
        type: string
    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      DIGITAL_OCEAN_SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    name: 'Deploy Frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Frontend
        uses: ./.github/actions/deploy-frontend
        with:
          domain: ${{ inputs.domain }}
          artifact_path: ${{ inputs.artifact_path }}
          droplet_ip: ${{ inputs.droplet_ip }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          DIGITAL_OCEAN_SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }} 