name: Deploy Frontend
description: 'Deploys the frontend application to the target environment'

on:
  workflow_call:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string
      droplet_ip:
        description: 'Digital Ocean Droplet IP'
        required: true
        type: string
    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      digital_ocean_ssh_private_key:
        required: true

jobs:
  deploy:
    name: 'Frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Frontend
        uses: ./.github/actions/deploy-frontend
        with:
          domain: ${{ inputs.domain }}
          droplet_ip: ${{ inputs.droplet_ip }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          digital_ocean_ssh_private_key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }} 