name: Deploy
description: 'Deploys the project architecture if not already deployed'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string
      frontend_repo:
        description: 'Frontend Repository URL (e.g., https://github.com/username/repo)'
        required: true
        type: string

jobs:
  validate:
    name: 'Validate'
    uses: ./.github/workflows/validate.yaml
    with:
      domain: ${{ inputs.domain }}
      frontend_repo: ${{ inputs.frontend_repo }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  manage-domains:
    name: 'Manage Domains'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Manage domains
        uses: ./.github/actions/manage_domains
        with:
          domain: ${{ inputs.domain }}

  run-terraform:
    name: 'Run Terraform'
    needs: [manage-domains, validate]
    runs-on: ubuntu-latest
    outputs:
      droplet_ip: ${{ steps.run-terraform.outputs.droplet_ip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform
        id: run-terraform
        uses: ./.github/actions/run_terraform
        with:
          domain: ${{ inputs.domain }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  build-frontend:
    name: 'Build Frontend'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Frontend
        uses: ./.github/actions/build_frontend
        with:
          frontend_repo: ${{ inputs.frontend_repo }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 

  deploy-frontend:
    name: 'Deploy Frontend'
    needs: [build-frontend, run-terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy_frontend
        with:
          domain: ${{ inputs.domain }}
          droplet_ip: ${{ needs.run-terraform.outputs.droplet_ip }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}