name: Deploy Infrastructure
description: 'Deploys the project architecture if not already deployed'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string

jobs:
  validate:
    name: 'Validate'
    uses: ./.github/workflows/validate.yaml
    with:
      domain: ${{ inputs.domain }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  terraform:
    name: 'Terraform'
    needs: validate
    uses: ./.github/workflows/terraform.yaml
    with:
      domain: ${{ inputs.domain }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}