name: Deploy
description: 'Deploys a new project to the serverless infrastructure'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string
      frontend_repo:
        description: 'Frontend Repository URL (e.g., https://github.com/username/repo)'
        required: true
        type: string

jobs:
  validate:
    name: 'Validate'
    uses: ./.github/workflows/validate.yaml
    with:
      domain: ${{ inputs.domain }}
      frontend_repo: ${{ inputs.frontend_repo }}
    secrets:
      cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  manage-domains:
    name: 'Manage Domains'
    needs: validate
    runs-on: ubuntu-latest
    outputs:
      domains: ${{ steps.manage-domains.outputs.domains }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Manage domains
        id: manage-domains
        uses: ./.github/actions/manage_domains
        with:
          domain: ${{ inputs.domain }}
          frontend_repo: ${{ inputs.frontend_repo }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  run-terraform:
    name: 'Run Terraform'
    needs: [manage-domains, validate]
    runs-on: ubuntu-latest
    outputs:
      auth_db_id: ${{ steps.run-terraform.outputs.auth_db_id }}
      domain_worker_names: ${{ steps.run-terraform.outputs.domain_worker_names }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform
        id: run-terraform
        uses: ./.github/actions/run_terraform
        with:
          domains: ${{ needs.manage-domains.outputs.domains }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-auth-service:
    name: 'Deploy Auth Service'
    needs: [run-terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Auth Service
        uses: ./.github/actions/deploy_auth_service
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          auth_db_id: ${{ needs.run-terraform.outputs.auth_db_id }}
          domain_worker_names: ${{ needs.run-terraform.outputs.domain_worker_names }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  deploy-domain-workers:
    name: 'Deploy Domain Workers'
    needs: [run-terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Domain Workers
        uses: ./.github/actions/deploy_domain_workers
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domain_worker_names: ${{ needs.run-terraform.outputs.domain_worker_names }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  deploy-pages:
    name: 'Deploy Pages'
    needs: [run-terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pages
        uses: ./.github/actions/deploy_pages
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  apply-auth-schema:
    name: 'Apply Auth Database Schema'
    needs: [run-terraform, deploy-auth-service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply Auth DB Schema
        uses: ./.github/actions/apply_auth_db_schema
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          auth_db_id: ${{ needs.run-terraform.outputs.auth_db_id }}
