name: Pre-Flight Checks
description: 'Checks that the domain is using Cloudflare nameservers and that the required Github secrets are present'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain Name'
        required: true
        type: string

jobs:
  check-nameservers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check nameservers
        uses: ./.github/actions/check_nameservers
        with:
          domain: ${{ github.event.inputs.domain }}
          
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Github Secrets
        uses: ./.github/actions/validate_secrets
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    # TODO: Add actions to create DNS records, load balancer, VM, HTTPS
    # Ensure we can reuse the same VM and load balancer for multiple domains

