name: Run Terraform

on:
    workflow_dispatch:
      inputs:
        domain:
          description: 'Domain Name'
          required: true
          type: string
    workflow_call:
      inputs:
        domain:
          description: 'Domain Name'
          required: true
          type: string

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        uses: ./.github/actions/terraform-init
        with:
          working-directory: terraform

      - name: Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          working-directory: terraform
          domain: ${{ inputs.domain }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          working-directory: terraform
          domain: ${{ inputs.domain }}
