name: Terraform
description: 'Initializes the Terraform working directory'

on:
    workflow_call:
      inputs:
        domain:
          description: 'Domain Name'
          required: true
          type: string
      secrets:
        CLOUDFLARE_ACCOUNT_ID:
          required: true
        CLOUDFLARE_API_TOKEN:
          required: true
        GH_PERSONAL_ACCESS_TOKEN:
          required: true

jobs:
  terraform-plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          domain: ${{ inputs.domain }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  terraform-apply:
    name: 'Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          domain: ${{ inputs.domain }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gh_personal_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}