name: Validate
description: 'Validates the deployment configuration'

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      frontend_repo:
        required: true
        type: string
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      BREVO_API_KEY:
        required: true
      STRIPE_SECRET_KEY:
        required: true
      STRIPE_WEBHOOK_SECRET:
        required: true

jobs:
  check-nameservers:
    name: 'Nameservers'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Cloudflare nameservers
        uses: ./.github/actions/check_cloudflare_nameservers
        with:
          domain: ${{ inputs.domain }}
          
  check-cloudflare-credentials:
    name: 'Cloudflare Access'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Github Secrets
        uses: ./.github/actions/validate_cloudflare_credentials
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  check-github-access:
    name: 'GitHub Access'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate GitHub Access
        uses: ./.github/actions/validate_github_access
        with:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  validate-frontend-repo:
    name: 'Frontend Repo'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate frontend repo
        uses: ./.github/actions/validate_frontend_repo
        with:
          frontend_repo: ${{ inputs.frontend_repo }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  validate-brevo-api-key:
    name: 'Brevo API Key'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Brevo API Key
        uses: ./.github/actions/validate_brevo_api_key
        with:
          brevo_api_key: ${{ secrets.BREVO_API_KEY }}

  validate-stripe-credentials:
    name: 'Stripe Credentials'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Stripe Credentials
        uses: ./.github/actions/validate_stripe_credentials
        with:
          stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}
          stripe_webhook_secret: ${{ secrets.STRIPE_WEBHOOK_SECRET }}


